name: Deploy
on:
  push:
    tags:
      - v*
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

      - uses: actions/cache@v2
        name: retrieve npm cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - name: run linter
        run: npm run lint

      - name: run library tests
        run: npm run test -- --coverage

      - name: build library
        run: npm run build -- --prod

      - name: run demo tests
        run: npm run test:demo

      - name: upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            dist
            coverage

  upload-coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: download build outputs
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-demo:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

      - uses: actions/cache@v2
        name: retrieve npm cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - name: download build outputs
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: build demo
        run: npm run build -- --prod --project=demo-app

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/demo-app

  publish-npm:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: download build outputs
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - uses: actions/setup-node@master
        with:
          registry-url: 'https://registry.npmjs.org/'

      - name: publish to npm
        working-directory: ./dist/ngx-kanban
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com/kevlatus'
          scope: '@kevlatus'

      - name: download build outputs
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: publish to Github Package Registry
        working-directory: ./dist/ngx-kanban
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
